### ISSUE TITLE
ge_pkg_versions

### ISSUE THREAD

**Issue by Pwoer-zy** [HopLee6/VJMHT#1]
Hello, I want to ask what the path name in the class means? Do you need to modify it to your own path?
dep_versions['display'] = run_command('cat/proc/driver/nvidia/version')
    print(dep_versions)
    dep_versions['cuda'] = 'NA'
    cuda_home = '/usr/local/cuda/'

**Comment by HopLee6** [comment]
Line 121 in `main.py` :
`print_pkg_versions()`
It is actually not important to our implementation and can be removed directly.

**Comment by Pwoer-zy** [comment]
> 中的121行`main.py`： `print_pkg_versions()` 其实对我们的实现并不重要，可以直接去掉。

Thank you very much, I will continue to study your code
